// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// IMPORTANT: Run `flutterfire configure` to generate real values.
/// These are placeholder values and must be replaced before running the app.
///
/// Example:
///   dart pub global activate flutterfire_cli
///   flutterfire configure
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIfMqnTP59FUvsyI21CbnQ7jFQqrHqy9U',
    appId: '1:360833149998:web:b017d4dbb993e4463243bf',
    messagingSenderId: '360833149998',
    projectId: 'skillforge-ai-4f2da',
    authDomain: 'skillforge-ai-4f2da.firebaseapp.com',
    storageBucket: 'skillforge-ai-4f2da.firebasestorage.app',
    measurementId: 'G-CF2MF2NQL5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXCYMlSuXgoMmYatqDNDIrO3O5BZji4Ko',
    appId: '1:360833149998:android:9763426b8c7b22f03243bf',
    messagingSenderId: '360833149998',
    projectId: 'skillforge-ai-4f2da',
    storageBucket: 'skillforge-ai-4f2da.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBthJw6eb9qJjRBsH5mYkarYimxuItcmGQ',
    appId: '1:360833149998:ios:4230a1390e06891a3243bf',
    messagingSenderId: '360833149998',
    projectId: 'skillforge-ai-4f2da',
    storageBucket: 'skillforge-ai-4f2da.firebasestorage.app',
    iosBundleId: 'com.skillforgeai.skillforgeAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIfMqnTP59FUvsyI21CbnQ7jFQqrHqy9U',
    appId: '1:360833149998:web:d5bcebf4985b31913243bf',
    messagingSenderId: '360833149998',
    projectId: 'skillforge-ai-4f2da',
    authDomain: 'skillforge-ai-4f2da.firebaseapp.com',
    storageBucket: 'skillforge-ai-4f2da.firebasestorage.app',
    measurementId: 'G-8MLZ4DHBQ8',
  );
}
